version: '2'
services:
  template-app:
    image: template
    depends_on:
      - template-postgresql
      - template-elasticsearch
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://template-postgresql:5432/template
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://template-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://template-elasticsearch:9200
    ports:
      - 8080:8080
  template-postgresql:
    extends:
      file: postgresql.yml
      service: template-postgresql
  template-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: template-elasticsearch
